'use strict';
const express = require('express');
const crypto = require('crypto');

function createTransitRouter({ db, admin, requireAuth, requireAdmin }) {
  const router = express.Router();
  const clean = (v, max = 300) => typeof v === 'string' ? v.replace(/[<>"'`\\]/g, '').trim().slice(0, max) : v;
  const id = v => clean(v, 120);
  const code = () => 'OKT-' + crypto.randomBytes(4).toString('hex').toUpperCase();
  const asStops = stops => Array.isArray(stops) ? stops.map((s,i)=>({id:clean(s.id || ('stop_'+(i+1)),80),name:clean(s.name,160),order:Number.isFinite(Number(s.order))?Number(s.order):i})).filter(s=>s.name) : [];
  function segmentFor(stops, pickupStopId, dropoffStopId) { const a=stops.findIndex(s=>s.id===pickupStopId); const b=stops.findIndex(s=>s.id===dropoffStopId); if(a<0||b<0||a>=b)return null; return {fromIndex:a,toIndex:b}; }
  async function activeBookings(tripId) { const snap=await db.collection('transit_bookings').where('tripId','==',tripId).get(); return snap.docs.map(d=>({id:d.id,...d.data()})).filter(b=>!['CANCELLED','EXPIRED'].includes(b.status)); }
  function seatsUsedBySegment(bookings, fromIndex, toIndex) { let used=0; for(const b of bookings){const a=Number(b.fromIndex),z=Number(b.toIndex);if(a<toIndex&&z>fromIndex)used+=Number(b.seatCount||1);} return used; }

  router.get('/routes', async (req,res)=>{try{const snap=await db.collection('transit_routes').where('active','==',true).limit(100).get();let routes=snap.docs.map(d=>({id:d.id,...d.data()}));const from=clean(req.query.from),to=clean(req.query.to);if(from)routes=routes.filter(r=>String(r.origin||'').toLowerCase().includes(from.toLowerCase()));if(to)routes=routes.filter(r=>String(r.destination||'').toLowerCase().includes(to.toLowerCase()));res.json({ok:true,routes});}catch(e){console.error('Transit routes:',e);res.status(500).json({error:'Unable to load transit routes'});}});
  router.get('/stations', async (_req,res)=>{try{const snap=await db.collection('transit_stations').where('active','==',true).limit(100).get();res.json({ok:true,stations:snap.docs.map(d=>({id:d.id,...d.data()}))});}catch(e){res.status(500).json({error:'Unable to load stations'});}});
  router.get('/search', async (req,res)=>{try{const routeId=id(req.query.routeId),date=clean(req.query.date,20);if(!routeId||!date)return res.status(400).json({error:'routeId and date required'});const routeSnap=await db.collection('transit_routes').doc(routeId).get();if(!routeSnap.exists)return res.status(404).json({error:'Route not found'});const route=routeSnap.data();const snap=await db.collection('transit_trips').where('routeId','==',routeId).where('serviceDate','==',date).get();const trips=[];for(const d of snap.docs){const trip={id:d.id,...d.data()};if(['CANCELLED','COMPLETED'].includes(trip.status))continue;const bookings=await activeBookings(d.id);const capacity=Number(trip.capacity||route.capacity||0);const bookedSeats=bookings.reduce((n,b)=>n+Number(b.seatCount||1),0);trips.push({...trip,route:{id:routeId,name:route.name,origin:route.origin,destination:route.destination},bookedSeats,availableSeats:Math.max(0,capacity-bookedSeats)});}trips.sort((a,b)=>String(a.departureTime).localeCompare(String(b.departureTime)));res.json({ok:true,trips});}catch(e){console.error('Transit search:',e);res.status(500).json({error:'Unable to search transit'});}});
  router.post('/book', requireAuth, async (req,res)=>{try{const {tripId,pickupStopId,dropoffStopId,seatCount=1,serviceClass='STANDARD'}=req.body;const seats=Math.max(1,Math.min(8,Number(seatCount)));const tripRef=db.collection('transit_trips').doc(id(tripId));const booking=await db.runTransaction(async tx=>{const tripSnap=await tx.get(tripRef);if(!tripSnap.exists)throw Object.assign(new Error('Trip not found'),{status:404});const trip=tripSnap.data();if(['CANCELLED','COMPLETED'].includes(trip.status))throw Object.assign(new Error('Trip is not bookable'),{status:409});const stops=asStops(trip.stops||[]),segment=segmentFor(stops,id(pickupStopId),id(dropoffStopId));if(!segment)throw Object.assign(new Error('Invalid pickup/drop-off stops'),{status:400});const bookingSnap=await db.collection('transit_bookings').where('tripId','==',tripRef.id).get();const used=seatsUsedBySegment(bookingSnap.docs.map(d=>d.data()),segment.fromIndex,segment.toIndex);const capacity=Number(trip.capacity||0);if(capacity<=0)throw Object.assign(new Error('Trip capacity not configured'),{status:409});if(used+seats>capacity)throw Object.assign(new Error('Not enough seats for this segment'),{status:409});const bookingRef=db.collection('transit_bookings').doc();const data={tripId:tripRef.id,passengerId:req.uid,pickupStopId:id(pickupStopId),dropoffStopId:id(dropoffStopId),fromIndex:segment.fromIndex,toIndex:segment.toIndex,seatCount:seats,serviceClass:clean(serviceClass,40)||'STANDARD',fare:Number(req.body.fare||0),currency:'GHS',status:'CONFIRMED',bookingCode:code(),createdAt:admin.firestore.FieldValue.serverTimestamp()};tx.set(bookingRef,data);return {id:bookingRef.id,...data};});res.status(201).json({ok:true,booking});}catch(e){console.error('Transit booking:',e);res.status(e.status||500).json({error:e.status?e.message:'Unable to book transit'});}});
  router.get('/bookings/:bookingId', requireAuth, async (req,res)=>{try{const snap=await db.collection('transit_bookings').doc(id(req.params.bookingId)).get();if(!snap.exists)return res.status(404).json({error:'Booking not found'});const b=snap.data();if(b.passengerId!==req.uid)return res.status(403).json({error:'Not your booking'});res.json({ok:true,booking:{id:snap.id,...b}});}catch(e){res.status(500).json({error:'Unable to load booking'});}});
  router.post('/bookings/:bookingId/cancel', requireAuth, async (req,res)=>{try{const ref=db.collection('transit_bookings').doc(id(req.params.bookingId)),snap=await ref.get();if(!snap.exists)return res.status(404).json({error:'Booking not found'});const b=snap.data();if(b.passengerId!==req.uid)return res.status(403).json({error:'Not your booking'});if(b.status!=='CONFIRMED')return res.status(409).json({error:'Booking is not active'});await ref.update({status:'CANCELLED',cancelledAt:admin.firestore.FieldValue.serverTimestamp(),cancelledReason:clean(req.body?.reason||'Passenger cancelled',200)});res.json({ok:true});}catch(e){res.status(500).json({error:'Unable to cancel booking'});}});
  router.post('/admin/stations', requireAdmin, async (req,res)=>{try{const name=clean(req.body.name,160);if(!name)return res.status(400).json({error:'Station name required'});const ref=await db.collection('transit_stations').add({name,city:clean(req.body.city,100)||'',region:clean(req.body.region,100)||'',address:clean(req.body.address,250)||'',active:req.body.active!==false,createdAt:admin.firestore.FieldValue.serverTimestamp(),createdBy:req.uid});res.status(201).json({ok:true,stationId:ref.id});}catch(e){res.status(500).json({error:'Unable to create station'});}});
  router.post('/admin/routes', requireAdmin, async (req,res)=>{try{const stops=asStops(req.body.stops);if(stops.length<2)return res.status(400).json({error:'At least two stops required'});const origin=clean(req.body.origin,160)||stops[0].name,destination=clean(req.body.destination,160)||stops[stops.length-1].name;const ref=await db.collection('transit_routes').add({name:clean(req.body.name,180)||(origin+' ↔ '+destination),origin,destination,stops,capacity:Math.max(1,Number(req.body.capacity||14)),serviceClass:clean(req.body.serviceClass,40)||'STANDARD',active:req.body.active!==false,estimatedDurationMinutes:Number(req.body.estimatedDurationMinutes||0),createdAt:admin.firestore.FieldValue.serverTimestamp(),createdBy:req.uid});res.status(201).json({ok:true,routeId:ref.id});}catch(e){res.status(500).json({error:'Unable to create route'});}});
  router.post('/admin/trips', requireAdmin, async (req,res)=>{try{const routeId=id(req.body.routeId),routeSnap=await db.collection('transit_routes').doc(routeId).get();if(!routeSnap.exists)return res.status(404).json({error:'Route not found'});const route=routeSnap.data();const ref=await db.collection('transit_trips').add({routeId,serviceDate:clean(req.body.serviceDate,20),departureTime:clean(req.body.departureTime,20),vehicleId:id(req.body.vehicleId)||null,driverId:id(req.body.driverId)||null,capacity:Math.max(1,Number(req.body.capacity||route.capacity||14)),stops:asStops(req.body.stops||route.stops),serviceClass:clean(req.body.serviceClass,40)||route.serviceClass||'STANDARD',status:'SCHEDULED',currentStopIndex:0,createdAt:admin.firestore.FieldValue.serverTimestamp(),createdBy:req.uid});res.status(201).json({ok:true,tripId:ref.id});}catch(e){res.status(500).json({error:'Unable to create trip'});}});
  return router;
}
module.exports = { createTransitRouter };